### ISSUE TITLE
Issue trying NGinx docker image

### ISSUE THREAD

**Issue by debu66er** [pivotal-cf/pcfdev#27]
I am trying to test docker support in Diego and I am facing issues because the ports used by the docker images. In my case, trying with NGinx:

cf push NGinx -o nginx

But it fails...

2016-02-01T10:31:26.61+0100 [CELL/0]     OUT Successfully created container
2016-02-01T10:31:26.61+0100 [CELL/0]     OUT Starting health monitoring of container
2016-02-01T10:31:27.17+0100 [HEALTH/0]   OUT healthcheck failed
2016-02-01T10:31:27.18+0100 [HEALTH/0]   OUT healthcheck passed
2016-02-01T10:31:27.18+0100 [HEALTH/0]   OUT Exit status 1
2016-02-01T10:31:27.19+0100 [HEALTH/0]   OUT Exit status 0
2016-02-01T10:31:27.72+0100 [HEALTH/0]   OUT healthcheck failed
...............
...............
2016-02-01T11:29:41.46+0100 [API/0]      OUT App instance exited with guid 35def1d1-1190-404d-ad85-075cff5945c1 payload: {"instance"=>"eeb17051-85a1-47ef-721d-1b61e068aa86", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"2 error(s) occurred:\n\n* 1 error(s) occurred:\n\n* Exited with status 1\n* 2 error(s) occurred:\n\n* cancelled\n* cancelled", "crash_count"=>3, "crash_timestamp"=>1454322581441417609, "version"=>"a9771553-ced6-40a4-8e2c-c9ff25af5282"}

When trying again I get:

Updating app NGinx in org micropcf-org / space micropcf-space as admin...
FAILED
Server error, status code: 400, error code: 100001, message: The app is invalid: ports Ports must be in the 1024-65535.

I understand the issue is that NGinx by default tries to use port 80.

Thanks in advance!

**Comment by sclevine** [comment]
Hi @debu66er, thanks for the report!

After some brief investigation, we think this may be an upstream bug with CC or routing. We have a story prioritized to investigate this further, and we'll let you know when we find out more.

**Comment by debu66er** [comment]
Great! Thank you very much.
I tested also Tomcat, Jetty and Liberty docker containers. All of them finished with errors by timeout but the routes seem to be up. But when testing the home pages I always get 404. This doesn't happen if I test the docker containers in a local standard docker installation.

Not sure if it is related or not with NGinx docker container issue as I don't get any error about port used. But they are other docker samples that seems not working properly.

Let me know if I can share any kind of log or test that can help you with the issue.

**Comment by davidwadden** [comment]
i reviewed the docker containers you listed, i didn't have a problem started tomcat and jetty, although jetty doesn't seem to have any pages available by default so that 404 is from the app itself (could confirm with `cf logs`)

liberty and nginx both have multiple `EXPOSE` ports, which i need to do some checking to see where we're at on supporting that.  i know the routing team has been involved.  i notice on the logs for these that healthchecks are firing against both ports 80 and 443, and maybe something is happening at the cloud controller layer preventing routes to ports < 1024.

**Comment by debu66er** [comment]
Thanks @davidwadden I revieved the tests with new v0.6.0 and:

Tomcat official Docker Image worked fine.
BTW, it is listening to port 80 although it exposes 8080. Is there anyway to specify a different port when deploying into CF?

NGinx official Docker image still failing with the same error:
`Server error, status code: 400, error code: 100001, message: The app is invalid: ports Ports must be in the 1024-65535.`

And WebSphere Liberty official Docker image tries to start because I get logs from it, but it seems it has a problem creating /log directory. Perhaps rights issues (although it runs fine in standard Docker runtime):
```
2016-02-10T21:09:22.31+0100 [CELL/0]     OUT Creating container
2016-02-10T21:09:26.62+0100 [CELL/0]     OUT Successfully created container
2016-02-10T21:09:26.62+0100 [CELL/0]     OUT Starting health monitoring of container
2016-02-10T21:09:27.54+0100 [APP/0]      OUT Launching defaultServer (WebSphere Application Server 8.5.5.8/wlp-1.0.11.cl50820151201-1942) on IBM J9 VM, version pxa6480sr1fp10-20150711_01 (SR1 FP10) (en_US)
2016-02-10T21:09:27.97+0100 [APP/0]      ERR TRAS0037E: The system could not create new file /logs
2016-02-10T21:09:27.98+0100 [APP/0]      OUT CWWKE0005E: The runtime environment could not be launched.
2016-02-10T21:09:27.98+0100 [APP/0]      OUT CWWKE0018E: An exception occurred while launching the runtime environment: java.lang.NullPointerException
2016-02-10T21:09:27.98+0100 [APP/0]      ERR com.ibm.ws.kernel.boot.LaunchException: Caught unexpected exception java.lang.NullPointerException
2016-02-10T21:09:27.98+0100 [APP/0]      ERR    at com.ibm.ws.kernel.boot.internal.KernelBootstrap.rethrowException(KernelBootstrap.java:524)
2016-02-10T21:09:27.98+0100 [APP/0]      ERR    at com.ibm.ws.kernel.boot.internal.KernelBootstrap.go(KernelBootstrap.java:207)
2016-02-10T21:09:27.98+0100 [APP/0]      ERR    at com.ibm.ws.kernel.boot.Launcher.handleActions(Launcher.java:245)
2016-02-10T21:09:27.98+0100 [APP/0]      ERR    at com.ibm.ws.kernel.boot.Launcher.createPlatform(Launcher.java:120)
2016-02-10T21:09:27.98+0100 [APP/0]      ERR    at com.ibm.ws.kernel.boot.Launcher.main(Launcher.java:55)
2016-02-10T21:09:27.98+0100 [APP/0]      ERR    at com.ibm.ws.kernel.boot.cmdline.EnvCheck.main(EnvCheck.java:61)
2016-02-10T21:09:27.98+0100 [APP/0]      ERR    at com.ibm.ws.kernel.boot.cmdline.EnvCheck.main(EnvCheck.java:37)
2016-02-10T21:09:27.98+0100 [APP/0]      ERR Caused by: java.lang.NullPointerException
2016-02-10T21:09:27.98+0100 [APP/0]      ERR    at com.ibm.ws.logging.internal.impl.LogProviderConfigImpl$InitConfgAttribute.getLogDirectory(LogProviderConfigImpl.java:387)
2016-02-10T21:09:27.98+0100 [APP/0]      ERR    at com.ibm.ws.logging.internal.impl.LogProviderConfigImpl.doCommonInit(LogProviderConfigImpl.java:173)
2016-02-10T21:09:27.98+0100 [APP/0]      ERR    at com.ibm.ws.logging.internal.impl.LogProviderConfigImpl.<init>(LogProviderConfigImpl.java:117)
2016-02-10T21:09:27.98+0100 [APP/0]      ERR    at com.ibm.ws.logging.internal.impl.LogProviderImpl.configure(LogProviderImpl.java:32)
2016-02-10T21:09:27.98+0100 [APP/0]      ERR    at com.ibm.ws.kernel.launch.internal.LauncherDelegateImpl.getLogProviderImpl(LauncherDelegateImpl.java:186)
2016-02-10T21:09:27.98+0100 [APP/0]      ERR    at com.ibm.ws.kernel.launch.internal.LauncherDelegateImpl.launchFramework(LauncherDelegateImpl.java:92)
2016-02-10T21:09:27.98+0100 [APP/0]      ERR    at com.ibm.ws.kernel.boot.internal.KernelBootstrap.go(KernelBootstrap.java:201)
2016-02-10T21:09:27.99+0100 [APP/0]      ERR    ... 5 more
2016-02-10T21:09:28.02+0100 [APP/0]      OUT Exit status 24
2016-02-10T21:09:28.02+0100 [CELL/0]     OUT Exit status 0
2016-02-10T21:09:28.04+0100 [API/0]      OUT App instance exited with guid efc25c36-8850-4c55-9517-e212807e84ee payload: {"instance"=>"b3978878-e91f-441a-4c55-1d6a2e5eb6d2", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"2 error(s) occurred:\n\n* 2 error(s) occurred:\n\n* Exited with status 24\n* cancelled\n* cancelled", "crash_count"=>4, "crash_timestamp"=>1455134968030522274, "version"=>"9d78ff6c-2d1d-4e2d-96cc-450b145f5c25"}
`

**Comment by alexvasseur** [comment]
Could you try with
cf push -o nginx ngx -u none
to disable health check?

I can't tell yet why health check does not pass but I could deploy the nginx official docker image this way.

I am curious about your use case though as Cloud Foundry provides an nginx buildpack already.
https://github.com/cloudfoundry/staticfile-buildpack

**Comment by alexvasseur** [comment]
For the WebSphere Liberty I could test it onto a full Pivotal Cloud Foundry installation.
Startup took about 2 minutes given all the installation that happens in this WebSphere Liberty image (https://github.com/docker-library/docs/blob/master/websphere-liberty/tag-details.md#websphere-libertywebprofile7 ) - and that was a fast datacenter network to download from the internet.
I have used:
cf push -o websphere-liberty:webProfile7 ly
After startup I can see logs as well as the welcome page for the WAS Liberty.
I will try on PCFdev later.

Note that IBM has a WAS Liberty builpack for Cloud Foundry since some time so you may also want to try it (cf push .. -b ...)
(2013) https://blog.pivotal.io/pivotal-cloud-foundry/products/ibm-liberty-buildpack-on-cloud-foundry
https://github.com/cloudfoundry/ibm-websphere-liberty-buildpack

**Comment by sclevine** [comment]
Closing this issue due to inactivity, and because we don't believe any remaining issues with the nginx Docker image are specific to PCF Dev.
